### PR TITLE
Fix/refactor tests

### LINKED ISSUE #24: Update test data source
Update tests to use a data source other than the data provided in the starter files

### PR DESCRIPTION
**Pull request by rdtho2525**
## Is this a fix or a feature? ⬇️
+ Fix

## What is the change? ⬇️
+ Removes source data presence in testing
+ Incorporates sample data

## What does it fix? ⬇️
+ N/A

## Where should the reviewer start? ⬇️
+ All test and class implementation files
+ Pay close attention to each class method as some may take in a new argument

## How should this be tested? ⬇️
+ Class implementation files should not import any data from the source files
+ All tests should be passing with the exception of 
+ Object functionality should persist

### CODE REVIEW

File: src/User.js [hunk 1]
```diff
@@ -49,11 +49,11 @@ class User {
     return this.removeDuplicates(recipes);
   }
 
-  filterByIngredients(searchString, list) {
+  filterByIngredients(searchString, list, ingredientArray) {
     const ingredients = searchString.split(',').map(tag => tag.trim());
```
Comment (JeffShepherd) [inline src/User.js:53]: Change required in scripts.js as a result of this change

File: src/RecipeRepo.js [hunk 2]
```diff
@@ -1,13 +1,12 @@
-const recipeData = require('../data/recipes');
 const Recipe = require('../src/Recipe');
 
 class RecipeRepo {
-  constructor() {
-    this.recipes = this.populateRecipes();
+  constructor(recipeArray) {
+    this.recipes = this.populateRecipes(recipeArray);
```
Comment (JeffShepherd) [inline src/RecipeRepo.js:5]: Necessitates update in scripts.js as a result of this change.

File: src/Recipe.js [hunk 3]
```diff
@@ -9,17 +7,23 @@ class Recipe {
...
   }
-  getIngredientNames() {
+  getIngredientNames(ingredientArray) {
     const name = this.ingredients.map(ingredient => {
-      const findName = ingredientsData.find(element => ingredient.id === element.id);
-      return findName.name;
+      const findName = ingredientArray.find(element => ingredient.id === element.id);
+      if (findName) {
+        return findName.name
+      }
```
Comment (JeffShepherd) [inline src/Recipe.js:15]: Necessitates change in scripts.js

File: src/Recipe.js [hunk 4]
```diff
@@ -9,17 +7,23 @@ class Recipe {
...
 
-  getTotalCostOfIngredients() {
+  getTotalCostOfIngredients(ingredientArray) {
     const cost = this.ingredients.reduce((totalCost, ingredient) => {
-      const findCost = ingredientsData.find(element => ingredient.id === element.id);
+      const findCost = ingredientArray.find(element => {
+        if (ingredient.id === element.id) {
+          return element.estimatedCostInCents
+        }
+      });
```
Comment (JeffShepherd) [inline src/Recipe.js:26]: Necessitates change in scripts.js

File: src/RecipeRepo.js [hunk 5]
```diff
@@ -1,13 +1,12 @@
...
   }
 
-  populateRecipes() {
-    const recipes = recipeData.map(recipe => new Recipe(recipe));
+  populateRecipes(recipeArray) {
+    const recipes = recipeArray.map(recipe => new Recipe(recipe));
```
Comment (JeffShepherd) [inline src/RecipeRepo.js:9]: Necessitates update in scripts.js as a result of this change.

**Review by JeffShepherd — APPROVED** [review]
Updates look good. Changes needed in scripts.js have been documented, and will be added in a future PR.
